/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Layout/Header.vue')['default'];
    Layout: typeof import('./src/components/Layout/index.vue')['default'];
    Menu: typeof import('./src/components/Layout/Menu.vue')['default'];
    PanoViewer: typeof import('./src/components/PanoViewer/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
